@GENERATED_WARNING@
FROM php:@DOCKER_FROM_TAG@

MAINTAINER Paweł Tomulik <ptomulik@@meil.pw.edu.pl>

@DOCKER_SAMI_ARGS@

ARG BUILD_DATE
ARG VCS_REF
ARG VERSION

LABEL org.label-schema.build-date="${BUILD_DATE}" \
      org.label-schema.name="Docker Sami Image" \
      org.label-schema.description="Docker image with Sami documentation generator. Designed to build PHP API docs for Korowai project." \
      org.label-schema.vcs-ref="${VCS_REF}" \
      org.label-schema.vcs-url="https://github.com/korowai/docker-sami" \
      org.label-schema.vendor="Paweł Tomulik" \
      org.label-schema.version="${VERSION}" \
      org.label-schema.schema-version="1.0"


@DOCKER_SAMI_ENV@

RUN set -xe && \
  apk add --no-cache --update inotify-tools git && \
  curl -s -L -o /usr/local/bin/sami http://get.sensiolabs.org/sami.phar && \
  chmod a+x /usr/local/bin/sami && \
  addgroup -g $SAMI_GID sami && \
  adduser -D -G sami -u $SAMI_UID sami

COPY bin/* /usr/local/bin/

VOLUME /home/sami/project

USER sami
COPY etc/sami.conf.php /home/sami/

WORKDIR /home/sami/project

ENTRYPOINT [ "sami-entrypoint" ]
CMD [ "autoserve" ]

EXPOSE $SAMI_SERVER_PORT
# vim: ft=dockerfile:
